---
apiVersion: v1
kind: Service
metadata:
  name: ep-mongo
spec:
  selector: {}
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      nodePort: 0
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ep-mongo
subsets:
  - addresses:
    - ip: 192.168.0.2
    ports:
    - port: 27017
      name: mongo
