---
apiVersion: v1
kind: Service
metadata:
  name: sails-frontend
spec:
  type: NodePort
  selector:
    app: sails
    tier: frontend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 32000
