apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
data:
  mongo.username: "username"
  mongo.password: "password"
  mongo.database: "admin"
  mongo.hostname: mongo.default.svc.cluster.local
  mongo.port: "27017"
