FROM  node:8.17.0 AS base

RUN apt-get update && apt-get install -y netcat
RUN npm install -g \
    sails \
    gulp \
    bower

WORKDIR /var/sails_workshop

# build frontend
FROM base AS frontend-base
EXPOSE 8000

COPY frontend/package.json ./
RUN npm install

COPY frontend/bower.json ./
RUN bower install -F --allow-root

COPY frontend/ .
CMD ["gulp"]
