FROM  node:8.17.0 AS base

RUN apt-get update && apt-get install -y netcat
RUN npm install -g \
    sails \
    gulp \
    bower

WORKDIR /var/sails_workshop

# build backend
FROM base AS backend-base
EXPOSE 1337

COPY backend/package.json backend/package-lock.json ./
RUN npm install

COPY backend/ .
CMD ["sails", "lift"]
