apiVersion: apps/v1
kind: Deployment
metadata:
  name: sails
  labels:
    app: sails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sails
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sails
    spec:
      containers:
      - name: sails
        image: sails-workshop-frontend:1.0.0
