---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: my-namespace
spec:
  containers:
    - name: centos
      image: centos
      args:
        - bash
        - -c
        - echo 'This is the only container' ; sleep 120 ; echo 'Bye bye!'
      resources:
        requests:
          memory: "500Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1"
  terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod2
  namespace: my-namespace
spec:
  containers:
    - name: centos
      image: centos
      args:
        - bash
        - -c
        - echo 'This is the only container' ; sleep 120 ; echo 'Bye bye!'
      resources:
        requests:
          memory: "500Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1"
  terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod3
  namespace: my-namespace
spec:
  containers:
    - name: centos
      image: centos
      args:
        - bash
        - -c
        - echo 'This is the only container' ; sleep 120 ; echo 'Bye bye!'
      resources:
        requests:
          memory: "500Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1"
  terminationGracePeriodSeconds: 5
