---
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: centos1
      image: centos
      args:
        - bash
        - -c
        - echo 'This is the 1st centos container' ; sleep 120 ; echo 'Bye bye centos1!'
    - name: centos2
      image: centos
      args:
        - bash
        - -c
        - echo 'This is the 2st centos container' ; sleep 60 ; echo 'Bye bye centos2!'
    - name: ubuntu1
      image: ubuntu
      args:
        - bash
        - -c
        - echo 'This is the 1st ubuntu container' ; sleep 120 ; echo 'Bye bye ubuntu1!'
    - name: ubuntu2
      image: ubuntu
      args:
        - bash
        - -c
        - echo 'This is the 2nd ubuntu container' ; sleep 60 ; echo 'Bye bye ubuntu2!'
  terminationGracePeriodSeconds: 5