---
apiVersion: v1
kind: Pod
metadata:
  name: message-app
  namespace: default
spec:
  containers:
    - name: message-app
      image: messageapp:0.1
      env:
        - name: MONGO_URL
          value: 'mongodb://172.17.0.2/messageApp'
      ports:
        - containerPort: 1337
          protocol: TCP
          name: sails
      command:
        - sails
      args:
        - lift
  terminationGracePeriodSeconds: 5